### ISSUE TITLE
when press the back button, it execute twice and then exit the app

### ISSUE THREAD

**Issue by Jackyaung** [Zhuinden/simple-stack#245] opened 2021-08-20 08:08 UTC
I set three tab, when go to tab2.1 from tab2, and then press the back button, it goes back first then exit the app (seems it execute twice), I'm new to android and especially navigation, anyone knows what the problem is ?

**Comment by Zhuinden** [comment] 2021-08-20 17:06
The last time I saw this happen to someone, the issue was that they called both `if(Navigator.onBackPressed(context)) {` AND `backstack.goBack()` (even though only the first is needed).

**Comment by Zhuinden** [comment] 2021-08-29 14:07
That doesn't look right, if you do this then you won't exit the app at all.

I believe what you are looking for is to try to dispatch the back event to the Fragment where the custom back behavior is needed, instead of immediately trying to navigate back using Simple-Stack (as the fragment wants to switch tab first).

For that, I used to use `findFragmentByTag` to check if the Fragment has `BackHandler` interface and then called `goBack()` and then returned if it was `return true`, but now you can actually use `requireActivity().onBackPressedDispatcher.addCallback(viewLifecycleOwner, object: Callback { })` from AndroidX to intercept back, too.

**Comment by Jackyaung** [comment] 2021-09-03 15:35
Hi @Zhuinden thanks for your info, that is very nice of you.

where should I use onBackPressedDispatcher ?  what you mean is , i need to use findFragmentByTag to find the Backhandler in every second lever of fragment , and then call requireActivity().onBackPressedDispatcher.addCallback(viewLifecycleOwner, object: Callback { }) ?

**Comment by Zhuinden** [comment] 2021-09-04 02:28
>  need to use findFragmentByTag to find the Backhandler in every second lever of fragment

You don't need that if you use the `requireActivity().onBackPressedDispatcher.addCallback(viewLifecycleOwner, object: Callback { })`

**Comment by Zhuinden** [comment] 2021-09-22 04:44
I'm just now realizing a flaw in how the back press dispatcher works in `ComponentActivity`.

I opened an issue for it.

https://github.com/Zhuinden/simple-stack/issues/248

Do you think this is the cause of your issue?

**Comment by ibrahimyilmaz** [comment] 2021-09-29 21:18
> @Zhuinden I think I solved it, I just change to below:
> 
> ```
> override fun onBackPressed() {
> ```
> 
> // if (Navigator.onBackPressed(this)){ // super.onBackPressed() // }
> 
> ```
>     Navigator.onBackPressed(this)
> 
> }
> ```

`onBackPressed` code doesn't seem right when we compared to the example in the readme.

*Example*
```kotlin
override fun onBackPressed() {
        if (!Navigator.onBackPressed(this)) {
            super.onBackPressed()
        }
    }
```

*Given*
```kotlin
override fun onBackPressed() {
    if (Navigator.onBackPressed(this))
        super.onBackPressed()
}
```

Given code should execute twice 

>I set three tab, when go to tab2.1 from tab2, and then press the back button, it goes back first then exit the app (seems it execute twice), I'm new to android and especially navigation, anyone knows what the problem is ?

**Comment by Zhuinden** [comment] 2021-09-30 23:53
Normally you'd need the !

**Comment by ibrahimyilmaz** [comment] 2021-10-01 17:44
@Zhuinden exactly! That's exactly what @Jackyaung  is missing in his code. 
So you can close this issue @Zhuinden.

**Comment by Zhuinden** [comment] 2021-10-01 20:51
Nice, glad to see it resolved

**Closed by Zhuinden** 2021-10-01 20:51 UTC
Labels: user support, done
