### ISSUE TITLE
FragmentStateChanger with show/hide does not trigger proper lifecycle

### ISSUE THREAD

**Issue by kakai248** [Zhuinden/simple-stack#133] opened 2018-12-19 15:28 UTC
This is not an issue with the library, it's more of a heads up.

In the MVP samples, the state changer uses attach/detach. This called lifecycle methods properly (up to onStart/onStop) but will destroy the fragment view.

In the MVVM sample, the state changer uses show/hide. This won't destroy the fragment view but it also won't do any lifecycle at all.

This means that all the LiveData's of all the opened fragments will keep observing as usual.

I'm not sure how to avoid this because afaik there isn't a way to keep the view and do regular lifecycle. I'm not a fan of destroying the view because state will get lost. Navigation library does this and they refuse to allow show/hide.

**Comment by Zhuinden** [comment] 2018-12-19 15:32
Hmm right LiveData would stay `active` even for fragments in the background.

But `detach` destroys the view hierarchy which can be expensive to create and noticeable while animating back.

Destroying the view with `detach` should not destroy the view because it does not call `onSaveInstanceState(Bundle` but it does call `view.saveHierarchyState` and preserves it.

Although if you're just observing *data* from a LiveData then receiving it even if you are not in foreground should not be a problem.

If you are observing commands like "please navigate" then that could be tricky.

I think removing and re-adding observers in `onHiddenChanged` would be excessive.

>  the state changer uses attach/detach.

ugh I should have changed this long ago

**Comment by kakai248** [comment] 2018-12-19 15:45
> Although if you're just observing data from a LiveData then receiving it even if you are not in foreground should not be a problem.

It was with an event that I noticed this. I have a BehaviorRelay that notifies when a model gets deleted. I have two screens (in the stack) that upon receiving this event should close. My events are propagated to the Fragment through a `LiveData<Event<Something>>`. This `Event` class makes sure events are only handled once. The first fragment receiving the event was actually the oldest one, which means that it will actually pop the newer fragment. So all in all, only one fragment gets popped.

I would have to build another system to propagate events instead of relying on LiveData. It would need a different lifecycle, which makes code hard to follow. But the main issue is still there and it's easy to fall into some sort of error because of this.

Fragments and their goddamn lifecycles -_-

**Comment by Zhuinden** [comment] 2018-12-19 15:51
I think LiveData is a decent replacement for BehaviorRelays, but trying to replace either PublishRelay or DispatchWorkSubject with LiveData is just asking for trouble.

Either way it kinda sucks that you are correct and you'd need a custom fragment lifecycle on top of the already existing fragment *and view* lifecycles that is also made inactive by `onHiddenChanged(false)`.

**Comment by Zhuinden** [comment] 2018-12-31 11:13
@yigit that makes me wonder though, any particular reason why `fragment.isHidden() == true` does not mean its Lifecycle is `inactive` by default?

**Comment by matejdro** [comment] 2019-02-05 15:15
How about something like that? https://gist.github.com/matejdro/4b2323158a5fd2b335c56500a9fee374

Basically we could create our own `LifecycleOwner` to use for LiveData that takes visibility into account. When calling `LiveData.observe()`, you would just pass `visibleViewLifecycle` as lifecycle owner.

**Comment by Zhuinden** [comment] 2019-02-05 15:55
The real magic with Fragments is that `onStop` is triggered when it is detached, even though the Activity around it is not stopped... Indeed, a combination of onHiddenChanged(true) or onStopped means that you're not in front.

I can't say anything about `setUserVisibilityHint`.

**Comment by matejdro** [comment] 2019-02-05 15:56
> `onStop` is triggered when it is detached, even though the Activity around it is not stopped

I would argue that this is correct behavior, since Fragment itself IS stopped.

**Comment by Zhuinden** [comment] 2019-02-05 16:10
So what of hidden? :D

**Comment by matejdro** [comment] 2019-02-05 16:11
Well, the issue is that even though fragment is no longer visible to the user, it does not trigger `onStop` by just hiding.

**Comment by matejdro** [comment] 2019-02-06 08:23
I think my current solution for this issue will be following:

1. Keep using hide/show version because going back is much smoother
2. Add `fragment.userVisibleHint = true/false` after every `fragmentTransaction.show/hide` call inside `FragmentStateChanger`. I'm not sure if that even helps with anything, but I guess it can't hurt.
3. Use https://gist.github.com/matejdro/4b2323158a5fd2b335c56500a9fee374 as base class for all fragments. This base provides custom lifecycle for LiveData and additional `onFragmentDisplayed` and `onFragmentHidden` callbacks that mimic existing `onStart/Stop` callbacks, but take visibility into acount.

**Comment by Zhuinden** [comment] 2019-02-06 11:42
@matejdro you could make onStart/onStop final in your base fragment.

**Comment by Zhuinden** [comment] 2019-02-06 11:51
Either way, I'm not really using `SingleLiveEvent` in these samples, and this is about fragment intricacies.

I think I'll close it.

**Comment by matejdro** [comment] 2019-02-06 12:30
Maybe a warning or notice somewhere in samples would be in order? People generally expect for Fragment lifecycles to happen, that is the whole point of Fragments.

**Comment by Zhuinden** [comment] 2019-02-06 12:40
Sigh, I guess I'll have to move the samples back to `detach/attach` again, although the layout inflation cost on back navigation can be noticeable.

IRL we used `show/hide` and it worked for us just fine. Honestly, the FragmentStateChanger you see here is very close to what we were doing apart from additionally keeping some other fragments added but hidden (for the bottom nav to be fast).

**Comment by matejdro** [comment] 2019-02-06 12:41
Yes, `show/hide` works fine, as long as you expect and know that lifecycle methods will not happen. I think leaving it at `show/hide` is fine, as long as it is noted in documentation.

**Comment by matejdro** [comment] 2019-04-25 18:46
It looks like this situation may be improved in future releases: https://issuetracker.google.com/issues/129780800

**Comment by Zhuinden** [comment] 2019-04-25 20:49
Lipstick on a pig... but it will definitely make it easier to combine the hidden state into onStop.

Good idea when it comes out :+1:

**Comment by kakai248** [comment] 2019-05-03 09:27
Can confirm `.setMaxLifecycle` fixes this.

Change all shows to:
```kotlin
fragmentTransaction
    .show(fragment)
    .setMaxLifecycle(fragment, Lifecycle.State.RESUMED)
```

And all hides to:
```kotlin
fragmentTransaction
    .hide(fragment)
    .setMaxLifecycle(fragment, Lifecycle.State.CREATED)
```

**Comment by Zhuinden** [comment] 2019-05-03 11:50
This requires `Version 1.1.0-alpha07`, correct?

I'll update the samples when I get to it, but I'm happy to hear it works. This `setMaxLifecycle` is tricky, but at least it works well!

**Comment by matejdro** [comment] 2019-05-03 11:59
Is `Lifecycle.State.RESUMED` enough to affect LiveData? If I recall correctly, fragment must not be started, not just not-resumed.

**Comment by kakai248** [comment] 2019-05-03 12:10
> This requires androidx.fragment:fragment:1.1.0-alpha07, correct?

Yes

> Is Lifecycle.State.RESUMED enough to affect LiveData? If I recall correctly, fragment must not be started, not just not-resumed.

RESUMED removes the restriction so the fragment can reach onResume again. 

CREATED doesn't let the fragment be on a started state so it's exactly what we need for LiveData. I tested it and you can see onStop being called.

**Comment by kakai248** [comment] 2019-05-17 13:11
In fragments version 1.1.0-alpha08, they changed the behavior of `setMaxLifecycle(fragment, Lifecycle.State.CREATED)` to destroy the view. [See this commit](https://android-review.googlesource.com/c/platform/frameworks/support/+/954180/)

This means that using show/hide in combination with `setMaxLifecycle` will no longer keep the view, which makes it worthless. We're back to where we started.

Either we use show/hide and lose lifecycle or just replace it altogether with attach/detach. We went with the latter.

**Comment by Zhuinden** [comment] 2019-05-17 14:16
Disappointing. No idea what to do about it then.

At this point, the solution might be to just not use fragments and use Views or Conductor instead. 🤔

**Comment by matejdro** [comment] 2019-05-18 04:48
@kakai248 Did you link to the right commit? The one you linked just seems to prevent fragments from stopping at ACTIVITY_CREATED.

**Comment by kakai248** [comment] 2019-05-18 11:13
@matejdro It means that they will no longer stop at `ACTIVITY_CREATED` and will go all the way back to `ON_CREATED`. According to [fragment lifecycle](https://static.javatpoint.com/images/androidimages/fragmentlifecycle.png), it means the view will have to be destroyed so it can reach that state.

Unless I'm mistaken. We were actually debugging other issue with the fragment view and started seeing a flicker after updating the dependency. Upon checking, `onDestroyView` was getting called, which was not supposed with show/hide.

**Comment by Zhuinden** [comment] 2019-05-18 13:17
They should just not re-use `Lifecycle.State` for this, because it doesn't match the Fragment lifecycle.

**Comment by matejdro** [comment] 2019-05-18 19:10
Maybe we should make an issue on issue tracker for this? Who knows, maybe planets align and they actually see the issue.

**Comment by Zhuinden** [comment] 2019-05-20 10:20
> Bug fixes
>
> - When using setMaxLifecycle(Lifecycle.State.CREATED), Fragments will properly have their view destroyed. [aosp/954180](https://android-review.googlesource.com/c/platform/frameworks/support/+/954180/)

:roll_eyes:

**Comment by matejdro** [comment] 2019-05-20 10:24
I have created ticket for that: https://issuetracker.google.com/issues/133100471

**Comment by matejdro** [comment] 2019-05-25 05:41
So, they closed the issue:

> This is working as intended in the current world of Fragments.

> The creation of a Fragment's view happens immediately before being started and cases where the Fragment is stopped, such as going onto the back stack, result in the Fragment's view being destroyed.

> We'll be working to combine the view and fragment lifecycles as part of https://issuetracker.google.com/issues/127528777

Maybe this combining of lifecycles could work in our favor?

**Comment by Zhuinden** [comment] 2019-05-25 07:07
Can barely wait for them to depreciate `setRetainInstance` for that, because that's the only way to do that :thinking_face:

Let's hope they don't start throwing exceptions for using platform level fragments. This wouldn't be the first time they break backwards compatibility in such a way (see region ops).

Either way, that means you really do need to define a custom visibility LifecycleOwner. :disappointed:

**Comment by matejdro** [comment] 2019-05-29 17:49
Hey, at least the future is bright:

> Once you opt in to combining the lifecycle (that future set of work linked in #4), Lifecycle.State.CREATED will mean that both the Fragment is created and the Fragment's View is created. That'll apply to all parts of FragmentManager including setMaxLifecycle().

**Comment by Zhuinden** [comment] 2019-10-28 14:26
@kakai248 https://twitter.com/ianhlake/status/1188821956033835008 🤔

**Comment by kakai248** [comment] 2019-10-28 15:33
Tbh with view recreation everything runs flawlessly (at least on my device, which is a fast one). And I take a simplification of the fragment lifecycle over keeping views any day.

**Comment by Zhuinden** [comment] 2019-10-28 15:34
It's kind of a pain if you have something heavier like a MapFragment for example, though.

**Comment by kakai248** [comment] 2019-10-28 20:08
That probably can be solved by AsyncLayoutInflater and MapView? Never tried it though. I'm not using maps extensively.

**Comment by matejdro** [comment] 2019-10-28 20:17
Would you even want to have MapView loaded in the background? It sounds like a lot of memory wasted just sitting in the backstack.

**Comment by Zhuinden** [comment] 2019-10-29 10:48
@matejdro sounds like a better UX than waiting for it to reload each time though, IIRC it loads for like 4 seconds.

**Comment by Zhuinden** [comment] 2019-10-29 11:18
In the end, this all boils down to that Google does not want to support visibility-based lifecycle owners, they want to kill `attach/detach` which might be quite awkward if you think about it (how will they know whether the Fragment state should survive? Are we to juggle using `setInitialSavedState`? how will it keep the ViewModelStore's ViewModel?).

I guess that's one more reason to use Rx instead of LiveData :wink:

**Closed by Zhuinden** 2019-10-29 11:18 UTC
Labels: design required, question, user support

**Comment by methelas** [comment] 2020-01-18 12:11
I know that this issue is closed for a while now... but what do you think about this solution to solve the hide/show lifecycle issue? It provides both regular and view-specific lifecycle owners that are aware of the `isHidden` status. It also checks whether any parent fragment is hidden too(if youre using nested fragments) since `onHiddenChaged` is not called for nested fragments while hiding parent fragment.
I think I'm a little bit over my head here, so if you see any issue with it, please let me know 🙈 

```kotlin
abstract class BaseFragment : Fragment() {

    //  LIFECYCLE OWNERS
    private val _hideableLifecycleOwner = HideableLifecycleOwner()
    val hideableLifecycle: LifecycleOwner get() = _hideableLifecycleOwner
    private val _hideableViewLifecycleOwner = HideableViewLifecycleOwner()
    val hideableViewLifecycle: LifecycleOwner get() = _hideableViewLifecycleOwner

    //  HIDDEN
    private var onHiddenOrParentHiddenChangedCalled = true
    private val isHiddenOrParentHidden: Boolean
        get() = isHidden || ((parentFragment as BaseFragment?)?.isHiddenOrParentHidden == true)
    private val _isHiddenForChildren = MutableLiveData(false)
    val isHiddenForChildren: LiveData<Boolean> = _isHiddenForChildren.distinctUntilChanged()

    // ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===
    // LIFECYCLE
    // ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        //  HIDDEN
        /* start listening to hide state changes of your direct parent(if exists) */
        (parentFragment as BaseFragment?)?.isHiddenForChildren?.observe(this, Observer {
            invokeOnHiddenOrParentHiddenChanged()
        })
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        //  LIFECYCLE OWNERS
        _hideableViewLifecycleOwner.initialize()
    }

    override fun onDestroyView() {
        //  LIFECYCLE OWNERS
        _hideableViewLifecycleOwner.deinitialize()
        super.onDestroyView()
    }

    override fun onDestroy() {
        //  HIDDEN
        (parentFragment as BaseFragment?)?.isHiddenForChildren?.removeObservers(this)
        super.onDestroy()
    }

    // ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===
    // HIDDEN
    // ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===

    final override fun onHiddenChanged(hidden: Boolean) {
        super.onHiddenChanged(hidden)
        invokeOnHiddenOrParentHiddenChanged()
    }


    private fun invokeOnHiddenOrParentHiddenChanged() {
        onHiddenOrParentHiddenChangedCalled = false
        onHiddenOrParentHiddenChanged(isHiddenOrParentHidden)
        if (!onHiddenOrParentHiddenChangedCalled)
            throw IllegalStateException("super.onHiddenOrParentHiddenChanged() not called!")
    }

    protected open fun onHiddenOrParentHiddenChanged(hidden: Boolean) {
        _hideableLifecycleOwner.onHiddenChanged(hidden)
        _hideableViewLifecycleOwner.onHiddenChanged(hidden)
        _isHiddenForChildren.value = hidden
        onHiddenOrParentHiddenChangedCalled = true
    }

    // ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===
    // ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===
    // LIFECYCLE OWNERS
    // ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===
    // ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===

    private inner class HideableLifecycleOwner : LifecycleOwner, LifecycleEventObserver {
        private val lifecycleRegistry = LifecycleRegistry(this)

        init {
            this@BaseFragment.lifecycle.addObserver(this)
        }

        override fun onStateChanged(source: LifecycleOwner, event: Lifecycle.Event) {
            when (event) {
                Lifecycle.Event.ON_START, Lifecycle.Event.ON_RESUME,
                Lifecycle.Event.ON_PAUSE, Lifecycle.Event.ON_STOP ->
                    lifecycleRegistry.handleLifecycleEvent(if (this@BaseFragment.isHiddenOrParentHidden) Lifecycle.Event.ON_STOP else event)
                else -> lifecycleRegistry.handleLifecycleEvent(event)
            }
        }

        internal fun onHiddenChanged(hidden: Boolean) {
            when {
                this@BaseFragment.lifecycle.currentState.isAtLeast(Lifecycle.State.STARTED) && hidden ->
                    lifecycleRegistry.handleLifecycleEvent(Lifecycle.Event.ON_STOP)
                this@BaseFragment.lifecycle.currentState.isAtLeast(Lifecycle.State.RESUMED) -> lifecycleRegistry.handleLifecycleEvent(Lifecycle.Event.ON_RESUME)
                this@BaseFragment.lifecycle.currentState.isAtLeast(Lifecycle.State.STARTED) -> lifecycleRegistry.handleLifecycleEvent(Lifecycle.Event.ON_START)
                this@BaseFragment.lifecycle.currentState.isAtLeast(Lifecycle.State.CREATED) -> lifecycleRegistry.handleLifecycleEvent(Lifecycle.Event.ON_CREATE)
            }
        }

        override fun getLifecycle(): Lifecycle = lifecycleRegistry
    }

    private inner class HideableViewLifecycleOwner : LifecycleOwner, LifecycleEventObserver {
        private var isInitialized = false
        private val lifecycleRegistry = LifecycleRegistry(this)

        fun initialize() {
            this@BaseFragment.viewLifecycleOwner.lifecycle.addObserver(this)
            isInitialized = true
        }

        fun deinitialize() {
            isInitialized = false
            this@BaseFragment.viewLifecycleOwner.lifecycle.removeObserver(this)
            lifecycleRegistry.handleLifecycleEvent(Lifecycle.Event.ON_DESTROY)
        }

        override fun onStateChanged(source: LifecycleOwner, event: Lifecycle.Event) {
            when (event) {
                Lifecycle.Event.ON_START, Lifecycle.Event.ON_RESUME,
                Lifecycle.Event.ON_PAUSE, Lifecycle.Event.ON_STOP ->
                    lifecycleRegistry.handleLifecycleEvent(if (this@BaseFragment.isHiddenOrParentHidden) Lifecycle.Event.ON_STOP else event)
                else -> lifecycleRegistry.handleLifecycleEvent(event)
            }
        }

        internal fun onHiddenChanged(hidden: Boolean) {
            if (!isInitialized) return
            when {
                this@BaseFragment.viewLifecycleOwner.lifecycle.currentState.isAtLeast(Lifecycle.State.STARTED) && hidden ->
                    lifecycleRegistry.handleLifecycleEvent(Lifecycle.Event.ON_STOP)
                this@BaseFragment.viewLifecycleOwner.lifecycle.currentState.isAtLeast(Lifecycle.State.RESUMED) -> lifecycleRegistry.handleLifecycleEvent(Lifecycle.Event.ON_RESUME)
                this@BaseFragment.viewLifecycleOwner.lifecycle.currentState.isAtLeast(Lifecycle.State.STARTED) -> lifecycleRegistry.handleLifecycleEvent(Lifecycle.Event.ON_START)
                this@BaseFragment.viewLifecycleOwner.lifecycle.currentState.isAtLeast(Lifecycle.State.CREATED) -> lifecycleRegistry.handleLifecycleEvent(Lifecycle.Event.ON_CREATE)
            }
        }

        override fun getLifecycle(): Lifecycle = lifecycleRegistry
    }
}
```

**Comment by matejdro** [comment] 2020-01-18 12:34
This could work, but even if you do it, `hide()` and `show() will be removed some time in the future, so you would be building your architure on already deprecated methods.

**Comment by Zhuinden** [comment] 2020-01-18 12:49
Technically they want to kill `attach` and `detach` too, because Ian Lake doesn't like them.

And whatever Navigation wants, Navigation gets.

Although IIRC it is possible to simulate `detach/attach` with `setMaxLifecycle(CREATED)`, so not all hope is lost.

As for that solution above, I'll try to look through it when I'm near a PC. I'm sure it can be simplified a bit using `viewLifecycleOwnerLiveData`.

**Comment by methelas** [comment] 2020-01-18 13:34
@Zhuinden I mean... if they really getting rid of hide/show then I just wasted my time trying to figure it out 🤔 
Should I just go for `attach/detach` approach for now?
And when they deprecate them too, will SimpleStack adjust?

**Comment by Zhuinden** [comment] 2020-01-18 14:17
>  if they really getting rid of hide/show then I just wasted my time trying to figure it out 

> Should I just go for attach/detach approach for now?

If you want to keep the view hierarchy as you navigate (which you probably do because re-inflation is costly), then you should keep your new `show/hide` approach :slightly_smiling_face: 

> And when they deprecate them too, will SimpleStack adjust?

Simple-Stack *itself* doesn't care as it is completely independent of whether you use Fragments, Views, or Conductor Controllers, or something completely different. The backstack / navigator do not depend on any behavior from the support library.

The *samples* will most likely need to adjust, although for the samples to adjust, Simple-Stack needs to shift to use AndroidX (currently I use the nullability annotations and those are still from `android.support.*`). I'd have to replace `detach/attach` with `setMaxLifecycle(CREATED/RESUMED`.

**Comment by methelas** [comment] 2020-01-18 18:32
@Zhuinden 
Thanks. I guess I'll go with hide/show for now, since at this point the app is pretty simple anyway.
And when the time comes I'll change it to more up-to-date solution.
